export 
const servicesData = [
  {
    header: "Nakkesmerter ",
    text: " Nakken består av sju virvler og en dens anatomi tilsier at den trenger mange leddbånd og muskler for å holde nakken oppreist. Allikevel er nakken er robust struktur og det trengs mye vold til for å skade strukturer i nakken. Nakkesmerter og ryggplager er det vanligste å oppsøke naprapat for. 50 % av oss får vondt i nakken under livet og til enhver tid har 13 % av befolkningen nakkeplager. Langvarige nakkeplager er vanligst hos kvinner og eldre, mens yngre heller får akutte plager. Ofte er det sånn at det verker eller hugger til, og en eller flere bevegelser er vonde å gjøre. Enkelte har så vondt at de knapt kommer seg opp av senga, og andre føler seg bare stive og spente. Noen opplever at smertene kom akutt, mens hos andre kom de smygende. Årsakene til at man får vondt i nakken er mange. Muskelkramper, muskelbristninger, prolaps (mindre vanlig i nakke enn i korsrygg), aldersmessige slitasjer, infeksjoner, betennelser og låsninger i ledd kan alle gi nakkeplager. I tillegg er nakken spesielt utsatt for stressplager som kan føre til at musklene strammer seg mer og man blir mindre tolerant for smerte. Noen av disse problemene også kan gi hodepine, svimmelhet eller stråle ned til skuldre eller helt ned til armen.",
  },

  {
    header: "Skulder ",
    text: "Skulderen er en komplisert struktur. Skulderen består av selve skulderleddet, leddet mellom kragebeinet og skulderbladet, og leddet mellom brystbenet og kragebeinet. Kravet om stor bevegelighet og mye kraft i skulderen er en vanskelig kombinasjon. I tillegg er man ofte ikke så flink til å styrke opp støttemuskulaturen. Smertene kan variere fra verkende smerter bak skulderbladet til huggende smerter inne i skulderleddet. Noen ganger kan smertene bli så ille at man knapt klarer å løfte armen. Mange opplever også at man ikke kan sove på den vonde armen.Årsakene til skuldersmerter varierer. Betennelser i sener eller slimposer, frakturer, avrevne leddbånd og sener, luksasjoner, slitasje og nerveinnklemninger er vanlige. I tillegg kan plager i nakken gi smerter til skulderen. Den vanligste årsaken er betennelser i sener i skulderen, også kalt impingment.Disse betennelsene oppstår ofte etter en over- eller feilbelastning. Noen ganger skyldes de rett og slett at passasjen for senene blir trangere med alderen. Det starter med en betennelse som kan vare i 3-4 uker, og kan utvikle seg til å bli en såkalt tendinose eller langvarig senebetennelse. Man får da vevsforandringer i senen med innvekst av blodårer, nerver og kalk, såkalt kalkskulder. Typisk for impingement er at armen er vond å løfte, kan hugge til i enkelte posisjoner og verke. Mange opplever også svakhet i skulder og arm. Mye statiske belastninger, arbeid over skulderhøyde eller fall er som regel årsaken til de fleste skulderplager.",
  },

  {
    header: " Albuesmerter  ",
    text: "Albuesmerter kan som regel deles inn i traumatiske skader (etter fall, slag eller kastbevegelse), eller plager etter repetitive belastninger som tennisalbue/musarm og golfalbue. Den vanligste lidelsen i albuen er tennisalbue/ musarm etterfulgt av golfalbue. Ved tennisalbue ligger smertene på yttersiden, mens ved golfalbue ligger smertene på innsiden. Begge tilstandene er senelidelser og kommer som regel etter langvarig ensidig belastning eller en akutt overbelastning. Selv om diagnosene har navn fra sport, forekommer de mye oftere ved ensidige arbeidsbelastninger som dataarbeid, håndverk eller hagearbeid. Typiske for disse plagene er smerter oppe ved seneinnfestningene som kan stråle utover. Mange opplever svakhet og kan slite med enkle hverdagsaktiviteter som å løfte kaffekanne eller holde en kopp. Man vil alltid starte en konsultasjon med å gjøre en sykehistorie for å prøve å finne ut om skaden har skjedd etter et traume (fall, slag) eller etter belastninger. Her kan man også finne ut om det er noe i hverdagen eller på arbeidsplassen som påvirker skaden i negativ grad og skal unngås for en periode. Etter sykehistorien gjør man ortopediske tester for å fastslå riktig diagnose. Behandlingen for albuesmerter varierer noe etter hva slags skade det er. Er det snakk om en skade på leddbåndene er det viktigste å trene opp funksjonen og styrken til albuen og omkringliggende strukturer. Hvis skaden sitter i senene har man mange ulike tiltak å velge mellom. Massasje, pressur, leddbehandling (manipulasjon), tøyninger og nåler er noen av teknikkene man kan gjøre. Er smertene mer langvarige kan man også behandle med trykkbølger for å stimulere legningen. ",
  },

  {
    header: "Kneplager",
    text: " Kneplager har mange årsaker og ulike plager kommer ofte ved ulike aldrea. Barn og unge er ofte plaget med smerter i senefestet under kneskåla. Idrettsutøvere får gjerne en smell eller takling og får skader på leddbåndene og menisker. Eldre har ofte slitasjeforandring på menisk og ledd, spesielt om de tidligere har hatt en kneskade.(med eller uten trykkbølgebehandling) og en god rehabilitering gi gode resultater.",
  },

  {
    header: "  Bekken ",
    text: " Smerter i bekken og hoftene er relativt vanlig og kan komme av mange årsaker. Mange kvinner opplever smerter i bekkenet under graviditet, eldre kan få slitasjeforandringer i hofteleddene, fotballkeepere som slenger seg og lander ofte på siden kan få slimposebetennelser og andre ganger kommer plagene fra korsryggen og sprer seg ned i hoftene. Symptomene kan variere mye fra sterke skjærende smerter ved hvert steg til knepplyder som kommer ved bestemte bevegelser (snapping hip), men uten smerter. En god undersøkelse kan i de fleste tilfeller faststille en diagnose.Bekkenløsning hos gravide kommer som et resultat at kroppen forbereder seg for fødsel og gjør leddbåndene mer elastiske. I tillegg får kroppen mer vekt som skal fordeles på ledd som allerede er mindre stabile. Enkle øvelser og manuell behandling bestående som regel av massasje, tøyninger, pressur og tips til selvbehandling gir erfaringsmessig god effekt.",
  },

  {
    header: "Hodepine",
    text: " Hodepine er noe de fleste er plaget med. I løpet av det siste året har 80 % hatt vondt i hodet og ca 5 % har vondt en eller flere ganger i uka. Det er sjeldent at en sykdom er årsaken til hodepinen. Det finnes mange typer hodepine. De vanligste typene hodepine er spenningshodepine og migrene. Spenningshodepine kommer som regel av stress og spente muskler i nakke og hode.Andre årsaken kan være problemer med synet og kjeveplager som spente tyggemuskler og skjevt bitt. Hodepinen er typisk pressende/klemmende/trykkende og kan ofte være på begge sider av hodet (panne og isse) og nakke. Typisk er at man føler et stramt bånd rundt hodet. Smertene er milde til moderate og det er som regel lite eller ingen kvalme og oppkast relatert til hodepinen, men det er ikke uvanlig med svimmelhet. Ofte varer hodepinen fra noen timer til en uke, men noen sliter også med kronisk spenningshodepine. Mange tar milde smertestillende av legen, men man skal vite at hyppig bruk av smertestillende kan gi kronisk hodepine, såkalt medikamentutløst hodepine. Migrene er en arvelig plage som rammer ca 10 % av den norske befolkningen. Og det er som regel kvinner som er plaget. Typisk for migrene er hodepine på en side som er pulserende og bankende. Hodepinene er moderat til sterk og varer som regel fra 4­72 timer. Hos noen innledes anfallet med aura, som er en synsfeltdefekt som vokser og vokser. Andre kan oppleve stikninger/prikkinger i ene kroppshalvdelen. Det er ikke uvanlig med kvalme og brekninger. Og mange er følsomme for lyd og lys. Migrene kan trigges av forstyrret søvnmønster, uregelmessig spisemønster, visse typer matvarer, fysiske og psykiske belastninger, værforandringer og sterke lukter. Det er en sterk sammenheng mellom migrene og spenningshodepine hvor det ene kan trigge det andre.",
  },
  {
    header: "Kneplager",
    text: " Kneplager har mange årsaker og ulike plager kommer ofte ved ulike aldrea. Barn og unge er ofte plaget med smerter i senefestet under kneskåla. Idrettsutøvere får gjerne en smell eller takling og får skader på leddbåndene og menisker. Eldre har ofte slitasjeforandring på menisk og ledd, spesielt om de tidligere har hatt en kneskade.(med eller uten trykkbølgebehandling) og en god rehabilitering gi gode resultater.",
  },

  {
    header: "  Bekken ",
    text: " Smerter i bekken og hoftene er relativt vanlig og kan komme av mange årsaker. Mange kvinner opplever smerter i bekkenet under graviditet, eldre kan få slitasjeforandringer i hofteleddene, fotballkeepere som slenger seg og lander ofte på siden kan få slimposebetennelser og andre ganger kommer plagene fra korsryggen og sprer seg ned i hoftene. Symptomene kan variere mye fra sterke skjærende smerter ved hvert steg til knepplyder som kommer ved bestemte bevegelser (snapping hip), men uten smerter. En god undersøkelse kan i de fleste tilfeller faststille en diagnose.Bekkenløsning hos gravide kommer som et resultat at kroppen forbereder seg for fødsel og gjør leddbåndene mer elastiske. I tillegg får kroppen mer vekt som skal fordeles på ledd som allerede er mindre stabile. Enkle øvelser og manuell behandling bestående som regel av massasje, tøyninger, pressur og tips til selvbehandling gir erfaringsmessig god effekt.",
  },

  {
    header: "Hodepine",
    text: " Hodepine er noe de fleste er plaget med. I løpet av det siste året har 80 % hatt vondt i hodet og ca 5 % har vondt en eller flere ganger i uka. Det er sjeldent at en sykdom er årsaken til hodepinen. Det finnes mange typer hodepine. De vanligste typene hodepine er spenningshodepine og migrene. Spenningshodepine kommer som regel av stress og spente muskler i nakke og hode.Andre årsaken kan være problemer med synet og kjeveplager som spente tyggemuskler og skjevt bitt. Hodepinen er typisk pressende/klemmende/trykkende og kan ofte være på begge sider av hodet (panne og isse) og nakke. Typisk er at man føler et stramt bånd rundt hodet. Smertene er milde til moderate og det er som regel lite eller ingen kvalme og oppkast relatert til hodepinen, men det er ikke uvanlig med svimmelhet. Ofte varer hodepinen fra noen timer til en uke, men noen sliter også med kronisk spenningshodepine. Mange tar milde smertestillende av legen, men man skal vite at hyppig bruk av smertestillende kan gi kronisk hodepine, såkalt medikamentutløst hodepine. Migrene er en arvelig plage som rammer ca 10 % av den norske befolkningen. Og det er som regel kvinner som er plaget. Typisk for migrene er hodepine på en side som er pulserende og bankende. Hodepinene er moderat til sterk og varer som regel fra 4­72 timer. Hos noen innledes anfallet med aura, som er en synsfeltdefekt som vokser og vokser. Andre kan oppleve stikninger/prikkinger i ene kroppshalvdelen. Det er ikke uvanlig med kvalme og brekninger. Og mange er følsomme for lyd og lys. Migrene kan trigges av forstyrret søvnmønster, uregelmessig spisemønster, visse typer matvarer, fysiske og psykiske belastninger, værforandringer og sterke lukter. Det er en sterk sammenheng mellom migrene og spenningshodepine hvor det ene kan trigge det andre.",
  },
  {
    header: "Hodepine",
    text: " Hodepine er noe de fleste er plaget med. I løpet av det siste året har 80 % hatt vondt i hodet og ca 5 % har vondt en eller flere ganger i uka. Det er sjeldent at en sykdom er årsaken til hodepinen. Det finnes mange typer hodepine. De vanligste typene hodepine er spenningshodepine og migrene. Spenningshodepine kommer som regel av stress og spente muskler i nakke og hode.Andre årsaken kan være problemer med synet og kjeveplager som spente tyggemuskler og skjevt bitt. Hodepinen er typisk pressende/klemmende/trykkende og kan ofte være på begge sider av hodet (panne og isse) og nakke. Typisk er at man føler et stramt bånd rundt hodet. Smertene er milde til moderate og det er som regel lite eller ingen kvalme og oppkast relatert til hodepinen, men det er ikke uvanlig med svimmelhet. Ofte varer hodepinen fra noen timer til en uke, men noen sliter også med kronisk spenningshodepine. Mange tar milde smertestillende av legen, men man skal vite at hyppig bruk av smertestillende kan gi kronisk hodepine, såkalt medikamentutløst hodepine. Migrene er en arvelig plage som rammer ca 10 % av den norske befolkningen. Og det er som regel kvinner som er plaget. Typisk for migrene er hodepine på en side som er pulserende og bankende. Hodepinene er moderat til sterk og varer som regel fra 4­72 timer. Hos noen innledes anfallet med aura, som er en synsfeltdefekt som vokser og vokser. Andre kan oppleve stikninger/prikkinger i ene kroppshalvdelen. Det er ikke uvanlig med kvalme og brekninger. Og mange er følsomme for lyd og lys. Migrene kan trigges av forstyrret søvnmønster, uregelmessig spisemønster, visse typer matvarer, fysiske og psykiske belastninger, værforandringer og sterke lukter. Det er en sterk sammenheng mellom migrene og spenningshodepine hvor det ene kan trigge det andre.",
  },
];